# This is a basic workflow to help you get started with Actions

name: Auto Reviewer

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const path = require('path')
            const scriptPath = path.resolve('./.github/scripts/auto-reviewer.js')
            console.log(require(scriptPath)({context}))
